[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.32.0"
egui = "0.32.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
shared = { path = "../shared" }