[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]

shared = { path = "../shared" }  # 路径依赖共享库
serde.workspace = true           # 引用工作区共享依赖
tokio.workspace = true
sqlx.workspace = true

