
// import { TabWidget } from "std-widgets.slint";

import { Icons } from "./assets/assets.slint";
import { SideBar } from "./sidebar.slint";
import { HomePage } from "./page/home.slint";
// import { KeyViewPage } from"./page/home.slint";
// import { TableViewPage } from"./page/keystone.slint";
// import { TextEditPage } from"./page/home.slint";
// import { EasingsPage } from"./page/home.slint";
// import { AboutPage } from"./page/about.slint";

import { Util } from "util.slint";

export component AppWindow inherits Window
{
    in-out property<int> active-tab: 0;

    // feedback 函数
    //callback handle_encrypt() => HomePage.handle_encrypt();

    // 窗体宽度和高度
    preferred-width: 1000px;
    preferred-height: 600px;

    title: @tr("Secure Tools");
    icon:Icons.logo;
    background: #f0f0f0;

    MenuBar {
        Menu {
            title: @tr("MenuBar" => "File");
            MenuItem { title: @tr("MenuBar" => "Open"); }
            Menu {
                title: @tr("MenuBar" => "Open Recent");
                for x in 10: MenuItem { title: @tr("MenuBar" => "Recent {}", x+1);  }
            }
            //MenuSeparator {}
            MenuItem { title: @tr("MenuBar" => "Save"); }
            Menu {
                title: @tr("MenuBar" => "Save As");
                for x in 10: MenuItem { title: @tr("MenuBar" => "Name {}", x+1);  }
            }
        }
        Menu {
            title: @tr("MenuBar" => "Edit");
            MenuItem { title: @tr("MenuBar" => "Copy"); }
            MenuItem { title: @tr("MenuBar" => "Paste"); }
        }
    }
    HorizontalLayout {
        sidebar := SideBar {
            title: @tr("Loyss Studo");
            model: [@tr("Menu" => "Home"), @tr("Menu" => "ListView"), @tr("Menu" => "TableView"), @tr("Menu" => "TextEdit"), @tr("Menu" => "Easings"), @tr("Menu" => "About")];
        }
    
        if(sidebar.current-item == 0) : HomePage {}
        // if(side-bar.current-item == 1) : KeyViewPage {}
        // if(side-bar.current-item == 2) : TableViewPage {}
        // if(side-bar.current-item == 3) : TextEditPage {}
        // if(side-bar.current-item == 4) : EasingsPage {}
        // if(side-bar.current-item == 5) : AboutPage {}
    }
}
