
export global Util {
    callback hide-window();
    callback show-window();
    callback close-window();

    callback min-window(flag: bool);
    callback get-is-min-window() -> bool;

    callback max-window(flag: bool);
    callback get-is-max-window() -> bool;

    callback fullscreen(flag: bool);
    callback get-is-fullscreen() -> bool;

    callback update-window-size();
    callback set-window-center();
    
}
