name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable
    - name: Build workspace
      run: cargo build --workspace --release
    - name: Run server tests
      run: cargo test -p server
    - name: Run client tests
      run: cargo test -p client